#!/usr/bin/env bash
# Build TitanUsbHid.apk (no Gradle — aapt + javac + d8 + apksigner)
#
# ALLOW_ROOT=1  compile-time: Root.available() may exec su (dev Magisk lab only)
# ALLOW_ROOT=0  never exec su (lab_rootless + release product path)
# Default: 0 unless ROM_PROFILE=dev
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Android/Sdk}}"
BT=$(ls -d "$SDK"/build-tools/*/ 2>/dev/null | sort -V | tail -1)
PLATFORM=$(ls -d "$SDK"/platforms/android-* 2>/dev/null | sort -V | tail -1)
[ -n "$BT" ] && [ -n "$PLATFORM" ] || { echo "need Android SDK"; exit 1; }
export PATH="$HOME/.local/jdk-17/bin:$HOME/.local/jdk/bin:/usr/lib/jvm/java-17-openjdk/bin:$PATH"
JAVAC=$(command -v javac)
JAR=$(command -v jar)

# Compile-time root gate (hybrid Dev vs Release)
if [ -z "${ALLOW_ROOT:-}" ]; then
  if [ "${ROM_PROFILE:-}" = "dev" ]; then ALLOW_ROOT=1; else ALLOW_ROOT=0; fi
fi
case "$ALLOW_ROOT" in
  1|true|TRUE|yes|YES|on|ON) ALLOW_ROOT=1; ALLOW_ROOT_JAVA=true ;;
  *) ALLOW_ROOT=0; ALLOW_ROOT_JAVA=false ;;
esac

BUILD=$(mktemp -d)
trap 'rm -rf "$BUILD"' EXIT
mkdir -p "$BUILD"/{gen,obj}
"$BT/aapt" package -f -m -J "$BUILD/gen" -M "$ROOT/AndroidManifest.xml" -S "$ROOT/res" \
  -I "$PLATFORM/android.jar" -F "$BUILD/resources.ap_"
# BuildConfig — not generated by aapt; gate all su probes at compile time
mkdir -p "$BUILD/gen/com/titanus2/usbhid"
cat > "$BUILD/gen/com/titanus2/usbhid/BuildConfig.java" <<EOF
package com.titanus2.usbhid;
/** Generated by build.sh — do not edit. ALLOW_ROOT=${ALLOW_ROOT} */
public final class BuildConfig {
    public static final boolean ALLOW_ROOT = ${ALLOW_ROOT_JAVA};
    private BuildConfig() {}
}
EOF
# Shared framework client sources (apps/titan2_api)
API_SRC="$(cd "$ROOT/../titan2_api/src" 2>/dev/null && pwd || true)"
[ -n "$API_SRC" ] || { echo "missing apps/titan2_api/src"; exit 1; }
"$JAVAC" --release 17 -cp "$PLATFORM/android.jar" -d "$BUILD/obj" \
  $(find "$BUILD/gen" "$ROOT/src" "$API_SRC" -name '*.java')
(cd "$BUILD/obj" && "$JAR" cf "$BUILD/classes.jar" .)
"$BT/d8" --min-api 28 --output "$BUILD" "$BUILD/classes.jar"
cp "$BUILD/resources.ap_" "$BUILD/unsigned.apk"
(cd "$BUILD" && "$BT/aapt" add unsigned.apk classes.dex)
"$BT/zipalign" -f -p 4 "$BUILD/unsigned.apk" "$BUILD/aligned.apk"
KS="$ROOT/debug.keystore"
if [ ! -f "$KS" ]; then
  keytool -genkeypair -keystore "$KS" -storepass android -keypass android \
    -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=Titan2,O=titanus2,C=EU"
fi
"$BT/apksigner" sign --ks "$KS" --ks-pass pass:android --key-pass pass:android \
  --out "$ROOT/TitanUsbHid.apk" "$BUILD/aligned.apk"
echo "OK $ROOT/TitanUsbHid.apk ($(stat -c%s "$ROOT/TitanUsbHid.apk") bytes) ALLOW_ROOT=$ALLOW_ROOT"
