#!/usr/bin/env bash
# Build TitanControls-v2.apk (no Gradle — aapt + javac + d8 + apksigner)
#
# ALLOW_ROOT=1  Dev only: show lab Developer tools; su helpers allowed
# ALLOW_ROOT=0  lab_rootless + release: no root UI / no su even if Magisk later
# Default: 0 unless ROM_PROFILE=dev (lab_rootless is rootless)
#
# LAW: every build updates CHANGELOG.md and embeds assets/changelog.txt.
# Optional: CHANGELOG_NOTE="bullet text" prepends notes under this build stamp.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
# GNU find -P does not descend a command-line symlink. Workshop src → AtlasOS.
FIND="${FIND:-/usr/bin/find}"
[ -x "$FIND" ] || FIND=find
SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Android/Sdk}}"
BT=$(ls -d "$SDK"/build-tools/*/ 2>/dev/null | sort -V | tail -1)
PLATFORM=$(ls -d "$SDK"/platforms/android-* 2>/dev/null | sort -V | tail -1)
[ -n "$BT" ] && [ -n "$PLATFORM" ] || { echo "need Android SDK build-tools + platforms"; exit 1; }

# Prefer JDK 17 + jar
export PATH="$HOME/.local/jdk-17/bin:$HOME/.local/jdk/bin:/usr/lib/jvm/java-17-openjdk/bin:/usr/lib/jvm/java-11-openjdk/bin:$PATH"
JAVAC=$(command -v javac)
JAR=$(command -v jar)
[ -n "$JAVAC" ] || { echo "need javac"; exit 1; }
[ -n "$JAR" ] || { echo "need jar"; exit 1; }

# Compile-time root gate (hybrid Dev vs Release)
if [ -z "${ALLOW_ROOT:-}" ]; then
  if [ "${ROM_PROFILE:-}" = "dev" ]; then ALLOW_ROOT=1; else ALLOW_ROOT=0; fi
fi
case "$ALLOW_ROOT" in
  1|true|TRUE|yes|YES|on|ON) ALLOW_ROOT=1; ALLOW_ROOT_JAVA=true ;;
  *) ALLOW_ROOT=0; ALLOW_ROOT_JAVA=false ;;
esac

# --- Manifest version (SoT for stamp + BuildConfig) ---
MANIFEST="$ROOT/AndroidManifest.xml"
VERSION_CODE=$(sed -n 's/.*android:versionCode="\([0-9]*\)".*/\1/p' "$MANIFEST" | head -1)
VERSION_NAME=$(sed -n 's/.*android:versionName="\([^"]*\)".*/\1/p' "$MANIFEST" | head -1)
[ -n "$VERSION_CODE" ] && [ -n "$VERSION_NAME" ] \
  || { echo "build.sh: need versionCode/versionName in AndroidManifest.xml"; exit 1; }

# --- LAW: stamp CHANGELOG.md on every build ---
CL="$ROOT/CHANGELOG.md"
[ -f "$CL" ] || {
  cat >"$CL" <<EOF
# Titan Controls — changelog

**LAW:** every \`build.sh\` run stamps this file and embeds \`assets/changelog.txt\`.

---
EOF
}
BUILD_UTC=$(date -u +%Y-%m-%dT%H:%MZ)
if ! head -40 "$CL" | grep -qE "\($VERSION_CODE\)"; then
  NOTES=""
  if [ -n "${CHANGELOG_NOTE:-}" ]; then
    NOTES=$(printf '%s\n' "$CHANGELOG_NOTE" | sed 's/^/- /')
  fi
  if [ -f "$ROOT/CHANGELOG_PENDING.md" ]; then
    NOTES="${NOTES}
$(grep -E '^\s*[-*]' "$ROOT/CHANGELOG_PENDING.md" 2>/dev/null || true)"
    rm -f "$ROOT/CHANGELOG_PENDING.md"
  fi
  [ -n "$NOTES" ] || NOTES="- Build stamp (ALLOW_ROOT=${ALLOW_ROOT})"
  {
    echo "# Titan Controls — changelog"
    echo ""
    echo "**LAW:** every \`build.sh\` run stamps this file and embeds \`assets/changelog.txt\`."
    echo "Do not ship without a matching build entry."
    echo ""
    echo "---"
    echo ""
    echo "## ${VERSION_NAME} (${VERSION_CODE}) — ${BUILD_UTC}"
    echo ""
    echo "$NOTES"
    echo ""
    echo "---"
    echo ""
    if grep -q '^## ' "$CL"; then
      awk 'BEGIN{s=0} /^## /{s=1} s{print}' "$CL"
    fi
  } >"$CL.new"
  mv -f "$CL.new" "$CL"
  echo "build.sh: CHANGELOG stamped ${VERSION_NAME} (${VERSION_CODE}) @ ${BUILD_UTC}"
else
  # Same versionCode rebuild: always record another stamp (LAW: every build updates)
  echo "build.sh: CHANGELOG rebuild stamp for (${VERSION_CODE})"
  {
    head -8 "$CL"
    echo ""
    echo "### rebuild ${BUILD_UTC} · ${VERSION_NAME} (${VERSION_CODE})"
    echo ""
    if [ -n "${CHANGELOG_NOTE:-}" ]; then
      printf '%s\n' "$CHANGELOG_NOTE" | sed 's/^/- /'
    else
      echo "- Rebuild (ALLOW_ROOT=${ALLOW_ROOT})"
    fi
    echo ""
    tail -n +9 "$CL"
  } >"$CL.new"
  mv -f "$CL.new" "$CL"
fi

mkdir -p "$ROOT/assets"
# Embed full changelog for in-app ChangelogActivity
cp -f "$CL" "$ROOT/assets/changelog.txt"
# Also stamp a one-line BUILD_ID for agents
printf 'versionName=%s\nversionCode=%s\nbuilt_utc=%s\nallow_root=%s\n' \
  "$VERSION_NAME" "$VERSION_CODE" "$BUILD_UTC" "$ALLOW_ROOT" \
  >"$ROOT/assets/build_id.txt"

BUILD=$(mktemp -d)
trap 'rm -rf "$BUILD"' EXIT
mkdir -p "$BUILD"/{gen,obj}

# aapt: include assets/ (changelog.txt LAW)
AAPT_ASSETS=()
if [ -d "$ROOT/assets" ]; then
  AAPT_ASSETS=(-A "$ROOT/assets")
fi
"$BT/aapt" package -f -m -J "$BUILD/gen" -M "$ROOT/AndroidManifest.xml" -S "$ROOT/res" \
  "${AAPT_ASSETS[@]}" \
  -I "$PLATFORM/android.jar" -F "$BUILD/resources.ap_"
rm -f "$ROOT/src/com/titanus2/controls/R.java"
# BuildConfig — version + root gate (generated; do not edit)
mkdir -p "$BUILD/gen/com/titanus2/controls"
cat > "$BUILD/gen/com/titanus2/controls/BuildConfig.java" <<EOF
package com.titanus2.controls;
/** Generated by build.sh — do not edit. ALLOW_ROOT=${ALLOW_ROOT} */
public final class BuildConfig {
    public static final boolean ALLOW_ROOT = ${ALLOW_ROOT_JAVA};
    public static final String VERSION_NAME = "${VERSION_NAME}";
    public static final int VERSION_CODE = ${VERSION_CODE};
    public static final String BUILD_UTC = "${BUILD_UTC}";
    private BuildConfig() {}
}
EOF
# Shared framework client sources (apps/titan2_api)
API_SRC="$(cd "$ROOT/../titan2_api/src" 2>/dev/null && pwd -P || true)"
[ -n "$API_SRC" ] || { echo "missing apps/titan2_api/src"; exit 1; }
# Locale/encoding: POSIX LC_ALL makes javac default US-ASCII and reject em-dash in comments.
export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"
mapfile -t _JAVAS < <("$FIND" -H "$BUILD/gen" "$ROOT/src" "$API_SRC" -name '*.java')
if [ "${#_JAVAS[@]}" -lt 40 ]; then
  echo "build.sh: only ${#_JAVAS[@]} java files — refusing hollow APK (src symlink?)" >&2
  exit 1
fi
"$JAVAC" --release 17 -encoding UTF-8 -cp "$PLATFORM/android.jar" -d "$BUILD/obj" \
  "${_JAVAS[@]}"
(cd "$BUILD/obj" && "$JAR" cf "$BUILD/classes.jar" .)
"$BT/d8" --min-api 28 --output "$BUILD" "$BUILD/classes.jar"
cp "$BUILD/resources.ap_" "$BUILD/unsigned.apk"
(cd "$BUILD" && "$BT/aapt" add unsigned.apk classes.dex)
"$BT/zipalign" -f -p 4 "$BUILD/unsigned.apk" "$BUILD/aligned.apk"
KS="$ROOT/debug.keystore"
if [ ! -f "$KS" ]; then
  keytool -genkeypair -keystore "$KS" -storepass android -keypass android \
    -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=Titan2,O=titanus2,C=EU"
fi
"$BT/apksigner" sign --ks "$KS" --ks-pass pass:android --key-pass pass:android \
  --out "$ROOT/TitanControls-v2.apk" "$BUILD/aligned.apk"
cp -f "$ROOT/TitanControls-v2.apk" "$ROOT/TitanControls.apk"
echo "OK $ROOT/TitanControls-v2.apk ($(stat -c%s "$ROOT/TitanControls-v2.apk") bytes) ALLOW_ROOT=$ALLOW_ROOT VERSION=${VERSION_NAME} (${VERSION_CODE}) changelog=assets/changelog.txt"
